datasets:
  minigpt4_pretrain:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /data1/vllm/MPP-LLaVA-Pretrain/cache/dataset/minigpt4/minigpt4_official_data.json
          storage: /data1/vllm/MPP-LLaVA-Pretrain/cache/dataset/minigpt4/minigpt4_official_data.json
      images:
          storage: /data1/vllm/MPP-LLaVA-Pretrain/cache/dataset/minigpt4/image
